const words =[
    ["vital", "முக்கிய"],
    ["pledge", "மேற்கோள்"],
    ["beyond", "மேம்பாடு"],
    ["martial art", "சாதனைக் கலை"],
    ["rectify", "சரிசெய்"],
    ["whatsoever", "எந்தவொரு"],
    ["legacy", "பிறப்பு"],
    ["ruthless", "கருத்தறிய"],
    ["somehow", "ஒருவிதமாக"],
    ["anyhow", "எப்படியேனும்"],
    ["sine", "சைன்"],
    ["anxious", "ஆசையான"],
    ["rant", "பேசு"],
    ["gratitude", "கிருத்தியுள்ளது"],
    ["barely", "அரிதாக"],
    ["ancient", "பழைய"],
    ["somewhat", "சில நிலையில்"],
    ["tolerate", "கண்டிப்பாக"],
    ["tragedy", "துக்கம்"],
    ["dirty mind", "கெட்ட மனம்"],
    ["embarrassing", "மகிழும்"],
    ["leads", "தலையிடுகின்றன"],
    ["orphan", "பெற்றோர் இல்லாத"],
    ["scold", "கையிருக்குகிறார்"],
    ["caution", "எச்சரிக்கை"],
    ["fame", "புகழ்"],
    ["horrible", "கொடுமையான"],
    ["polite", "கெட்டுப் பேசுகின்றன"],
    ["influence", "விளைவிக்கின்றன"],
    ["region", "பகுதி"],
    ["exhausted", "காலாண்டினால் கடைபிடித்த"],
    ["taken for granted", "அவசியமாக எடுத்துக்கொண்டுள்ளது"],
    ["residence", "வீட்டில்"],
    ["wisdom", "ஞானம்"],
    ["cornerstone", "முக்கிய அடிப்படை"],
    ["scenario", "சுவடு"],
    ["territory", "பகுதி"],
    ["terrible", "கொடுமையான"],
    ["critical", "முக்கியமான"],
    ["courage", "தடித்திருப்பது"],
    ["plenty", "பெரும்பாலும் உள்ள"],
    ["shame", "அவமர்ச்சியாக"],
    ["swelling", "வலி"],
    ["now or never", "இப்போது அல்லது ஒரு நேரமில்லை"],
    ["nothing", "ஒன்றுமில்லை"],
    ["something", "ஏதோ ஒன்று"],
    ["everything", "எல்லாம்"],
    ["anything", "எதையும்"],
    ["everyone", "அனைவரும்"],
    ["someone", "யாரோ"],
    ["anyone", "யாரேனும்"],
    ["However", "எனக்குப் பதில்"],
    ["Whatever", "எந்தவொருவாறும்"],
    ["Whichever", "எந்தப் பகுதிக்கும்"],
    ["Wherever", "எங்கும்"],
    ["Whensoever", "எப்போதும் எப்போதும்"],
    ["Nevertheless", "இப்போதும்"],
    ["Nonetheless", "இப்போதும்"],
    ["Forever", "எப்போதும்"],
    ["Henceforth", "அந்த நிலைக்கு பின்னர்"],
    ["Whatever's", "எந்தவொருவாறும்"],
    ["Nonetheless", "இப்போதும்"],
    ["Whencesoever", "எங்கிருந்தும்"],
]

export default words;
