const words =[  ["isn't it?", "ஆமாம் தானே ?"],
  ["bearable", "தாங்கக்கூடிய"],
  ["unbearable", "தாங்க முடியாத"],
  ["borrow", "கடன் வாங்கு"],
  ["mighty", "வலிமை மிக்க"],
  ["vital", "அத்தியாவசியமான"],
  ["pledge", "உறுதிமொழி"],
  ["beyond", "அப்பாற்பட்டது"],
  ["martial art", "தற்காப்புக் கலை"],
  ["rectify", "திருத்து"],
  ["whatsoever", "எதுவும் இல்லை"],
  ["legacy", "மரபு"],
  ["ruthless", "கொடூரமான"],
  ["somehow", "எப்படியாவது"],
  ["anyhow", "எப்படியோ"],
  ["sine", "சீன்"],
  ["anxious", "பதட்டமான"],
  ["rant", "திட்டு"],
  ["gratitude", "நன்றியுணர்வு"],
  ["barely", "வெறும்"],
  ["ancient", "பழமையான"],
  ["somewhat", "ஓரளவு"],
  ["tolerate", "பொறுத்துக்கொள்"],
  ["tragedy", "துயரம்"],
  ["dirty mind", "அசுத்தமான மனம்"],
  ["embarrassing", "சங்கடமான"],
  ["leads", "இட்டுச் செல்கிறது"],
  ["orphan", "அநாதை"],
  ["scold", "கடிந்துகொள்"],
  ["caution", "எச்சரிக்கை"],
  ["fame", "புகழ்"],
  ["horrible", "பயங்கரமான"],
  ["polite", "கனிவான"],
  ["influence", "செல்வாக்கு"],
  ["embarrassing", "சங்கடமான"],
  ["region", "மண்டலம்"],
  ["exhausted", "சோர்வடைந்த"],
  ["taken for granted", "சர்வ சாதாரணமாக எடுத்துக்கொள்ளப்பட்ட"],
  ["residence", "வசிப்பிடம்"],
  ["wisdom", "ஞானம்"],
  ["cornerstone", "அஸ்திவாரம்"],
  ["scenario", "சூழ்நிலை"],
  ["territory", "பிரதேசம்"],
  ["terrible", "பயங்கரமான"],
  ["critical", "முக்கியமான"],
  ["courage", "தைரியம்"],
  ["plenty", "நிறைய"],
  ["shame", "வெட்கம்"],
  ["swelling", "வீக்கம்"],
  ["now or never", "இப்போது அல்லது ஒருபோதும்"],
  ["nothing", "ஒன்றுமில்லை"],
  ["something", "ஏதோ ஒன்றை"],
  ["everything", "எல்லாமே"],
  ["anything", "எதுவும்"],
  ["everyone", "எல்லோரும்"],
  ["someone", "யாரோ ஒருவர்"],
  ["anyone", "யாராவது"],
  ["However", "இருப்பினும்"],
  ["Whatever", "எதுவாக இருந்தாலும்"],
  ["Whichever", "எதுவாக இருந்தாலும்"],
  ["Wherever", "எங்கு வேண்டுமானாலும்"],
  ["Whensoever", "எப்போது வேண்டுமானாலும்"],
  ["Nevertheless", "ஆயினும்"],
  ["Nonetheless", "இருப்பினும்"],
  ["Forever", "என்றென்றும்"],
  ["Henceforth", "இதுமுதல்"],
  ["Whatever's", "எதுவாக இருந்தாலும்"],
  ["Nonetheless", "இருப்பினும்"],
  ["Whencesoever", "எங்கிருந்து வேண்டுமானாலும்"],
  ["headache", "தலைவலி"],
  ["storm", "புயல்"],
  ["day in day out", "தினமும்"],
  ["only then", "பின்பு மட்டுமே"],
  ["fortunate", "அதிர்ஷ்டசாலி"],
  ["aggressive", "ஆக்கிரமிப்பு"],
  ["aggressiveness", "ஆக்கிரமிப்புத்தன்மை"],
  ["intimidate", "மிரட்டு"],
  ["do you ever", "நீ எப்போதாவது"],
  ["seemingly", "வெளிப்படையாக"],
  ["modern", "நவீன"],
  ["lack", "பற்றாக்குறை"],
  ["instinct", "உள்ளுணர்வு"],
  ["decades", "தசாப்தங்கள்"],
  ["intend", "நோக்கம்"],
  ["intended", "நோக்கமாக இருந்தது"],
  ["intend to", "நோக்கம்"],
  ["indeed", "உண்மையில்"],
  ["wise", "ஞானமான"],
  ["further", "மேலும்"],
  ["facilitate", "எளிதாக்கு"],
  ["aid", "உதவி"],
  ["rather", "மாறாக"],
  ["rather be", "மாறாக இருக்க வேண்டும்"],
  ["rather not say", "சொல்ல விரும்பவில்லை"],
  ["engaging", "ஈர்க்கும்"],
  ["fantasy", "கற்பனை"],
  ["toxic", "நச்சுத்தன்மையுள்ள"],
  ["even though", "அப்படியே"],
  ["enthusiasm", "உற்சாகம்"],
  ["negotiation", "பேச்சுவார்த்தை"],
  ["reservation", "பதிவு செய்தல்"],
  ["forbidden", "தடைசெய்யப்பட்ட"],
  ["morality", "ஒழுக்கம்"],
  ["however", "இருப்பினும்"],
  ["swear", "சத்தியம் செய்"],
  ["suck", "உறிஞ்சு"],
  ["threshold", "அளவுகோல்"],
  ["migration", "இடம்பெயர்வு"],
  ["immigration", "குடியேற்றம்"],
  ["abuse", "துஷ்பிரயோகம்"],
  ["abusive", "கொடுமைப்படுத்தும்"],
  ["democracy", "ஜனநாயகம்"],
  ["soaking", "நனைத்தல்"],
  ["scrape", "கீறல்"],
  ["leftover", "மீதி"],
  ["through", "வழியாக"],
  ["throughout", "முழுவதும்"],
  ["throughput", "ஊடுருவல்"],
  ["dump", "தூக்கி எறி"],
  ["dumping", "தூக்கி எறிதல்"],
  ["macho", "ஆண்மை"],
  ["macho man", "ஆண்மை மனிதன்"],
  ["rush", "அவசரம்"],
  ["hesitated", "தயங்கினார்"],
  ["certainly", "நிச்சயமாக"],
  ["absolutely", "முற்றிலும்"],
  ["so much", "அவ்வளவு"],
  ["too much", "அதிகம்"],
  ["not at all", "இல்லையே"],
  ["not at least", "குறைந்தபட்சம் இல்லை"],
  ["not yet", "இன்னும் இல்லை"],
  ["not so", "அவ்வளவு இல்லை"],
  ["if so", "அப்படியானால்"],
  ["if not", "இல்லையெனில்"],
  ["nothing else", "வேறு எதுவும் இல்லை"],
  ["nobody else", "வேறு யாரும் இல்லை"],
  ["what else", "வேறு என்ன"],
  ["dignity", "கண்ணியம்"],
  ["literally", "அச்சடியாக"],
  ["meanwhile", "இதற்கிடையில்"],
  ["eventually", "இறுதியில்"],
  ["nowhere", "எங்கும் இல்லை"],
  ["somewhere", "எங்காவது"],
  ["possession", "உடைமை"],
  ["glory", "புகழ்"],
  ["thirst", "தாகம்"],
  ["nostalgic", "பழமையான"],
  ["disinfect", "கிருமி நீக்கம் செய்"],
  ["commute", "போக்குவரத்து"],
  ["funeral", "இறுதிச் சடங்கு"],
  ["dispatch", "அனுப்பு"],
  ["dawn", "விடியல்"],
  ["traitor", "துரோகி"],
  ["manifest", "வெளிப்படுத்த"],
  ["betrayal", "துரோகம்"],
  ["certain", "நிச்சயமான"],
  ["uncertainty", "நிச்சயமற்ற தன்மை"],
  ["avoid", "தவிர்க்க"],
  ["instinct", "உள்ளுணர்வு"],
  ["setback", "பின்னடைவு"],
  ["stolen", "திருடப்பட்டது"],
  ["criteria", "அளவுகோல்கள்"],
  ["might be", "இருக்கலாம்"],
  ["might have", "இருக்கலாம்"],
  ["might have gone", "சென்றிருக்கலாம்"],
  ["warn", "எச்சரிக்கை"],
  ["vary", "மாறுபடும்"],
  ["faith", "நம்பிக்கை"],
  ["confession", "ஒப்புதல்"],
  ["sustain", "நிலைபெற"],
  ["compassion", "பரிதாபம்"],
  ["hesitate", "தயங்க"],
  ["brought", "கொண்டு வந்தது"],
  ["bought", "வாங்கியது"],
  ["feign", "பாசாங்கு செய்"],
  ["procrastination", "தள்ளிப்போடுதல்"]
]

export default words;
